### PR TITLE
Read multitouch events only if pointer events are not available

### PR DESCRIPTION
**Pull request by falstaff84**
Commit c525c0b5d8ea ("Support reading coordinates from multitouch
devices.") introduced reading of multitouch events. However, if
both event types are available a mix of the two was used. On
devices which report a second touch simultaneously (even if not
touched), this can lead to unuseable touch inputs.

Most multitouch drivers provide pointer emulation (e.g. through
kernels input stack function input_mt_report_pointer_emulation).
Hence prefer the pointer device coordinates if announced.

Note: This does not solve the issue if drivers reporting two
multitouch coordinates. There is more work needed to support
multitouch only devices properly.

### CODE REVIEW

**Comment by jaretcantu** [comment]
Something seems off with your patch:

```diff
-       if ((ioctl(ts->fd, EVIOCGBIT(EV_ABS, sizeof(absbit)), absbit)) < 0 ||
```
originally was a condition _for failure_. In your change:

```diff
+       if ((ioctl(ts->fd, EVIOCGBIT(EV_ABS, sizeof(absbit)), absbit)) < 0) {
```
is the condition _to check_ for ABS support.

This means that if the ioctl fails (< 0), check_fd() will only eventually fail because absbit[] is not set.
This also means that if the ioctl succeeds (>= 0), using_mt will not be set, which is quite the opposite of what you want to happen. Only if the EV_ABS ioctl succeeds will absbit[] even be set to determine how to set using_mt.

There should be two points of failure: if the EV_ABS ioctl check fails and if no ABS_*X/Y pairs are supported. See 1b2fbcb0a8bdf15ae0b054697e494ca1fe4c7699 for my recommended changes.

**Comment by falstaff84** [comment]
Just looked over the code again, I fully agree with you. Your patch fixes it so it does the right thing. @kergoth Shall I create a new pull request or can you apply both changes at once?

**Comment by merge** [comment]
Thanks for your suggestens. To be honest, I think this doesn't add real value now. Multitouch devices often also report ABS_X/ABS_Y, and if they don't, we already take ABS_MT_POSITION_ too. If both are reported, and are different values, well, we overwrite. But we don't have multitouch support yet and our behaviour is equally usable right now.

I'm working on multitouch support, so I wouldn't change our existing singletouch ts_read() right now.

**Comment by falstaff84** [comment]
It is a while since I posted the patch, so I don't remember the exact details, but I remember that our touchscreen reported both and it did not work properly.

Unfortunately, we **do not** overwrite! This events can be reported independently by the kernel. The code mixes the two (takes one event from the multi touch values, and then one from absolute values)... This ended up in a jumpy/unusable mouse pointer.

**Pull request closed without merging**
