### PR TITLE
ts_find: extended list of predefined touchscreen devices

### PR DESCRIPTION
**Pull request by filug**
In case when touchscreen name is NOT defined by TSLIB_TSDEVICE
tslib will automatically test following devices:

- /dev/input/ts,
- /dev/input/touchscreen,
- /dev/input/event0,
- /dev/touchscreen/ucb1x00.

PR as discussed in #61. 
Added `/dev/input/ts` to extend compatibility between tslib and boundarydevices fork.

### CODE REVIEW

**Comment by merge** [comment]
I like it. But since you brought it up, if there already is boundarydevices' new API call, why not add https://github.com/boundarydevices/tslib/commit/c6351355736d9dd8e7f1aff56124860ac9859fb3 or something compatible?

Thanks!

**Comment by filug** [comment]
You are right. I've found boundarydevices fork just before this PR and the only thing I've done with it is to reuse `/dev/input/ts` device.

I agree that instead new `ts_find` we can call this function `ts_open_config` + I like `is_touchscreen` in the `for` loop. In my implementation `/dev/touchscreen/ucb1x00` will be not touched in case when `/dev/input/event0` exists (but is not a touchscreen device).

I can fix my implementation. The only thing I have in my mind is incompatible function prototype:

- in the past it was `struct tsdev *ts_open_config(int nonblock)`,
- right now it is `struct tsdev *ts_open_config(int nonblock, int xres, int yres)`.

The first one is completely fine with _mainline tslib_ point of view but is not compatible with the latest _boundarydevices_ API. Second will add additional effort each time when somebody will try to call `ts_open_config`.

**Comment by merge** [comment]
True. I hadn't checked their current state. I would add ts_config, but in this case I'd invent a new name for this wrapper API. `ts_find_open_config()` describing what it does (but doesn't it sound like finding and open configuration? :), or `ts_setup()` ?

If you add it, please remember to adapt `is_touchscreen()` for multitouch-only devices (like we do in input-raw for example).

**Comment by merge** [comment]
Actually please don't add `is_touchscreen()` here. This is and should be decided by the raw plugin dealing with hardware.

**Comment by merge** [comment]
To make it clear: I think i'd take it if you rename it to` ts_setup()` and include the `ts_config()` call (removing it from all the calling programs). thanks!

**Comment by filug** [comment]
Fine with me. I'll correct it as you suggest and I'll update this PR.

**Comment by filug** [comment]
I have some issues with following suggestion

> ... and include the ts_config() call (removing it from all the calling programs)

According to my changes in case when touchscreen name is defined by user "old" `ts_open` function is called; if ts name is not defined I'm trying to discover it by the `ts_find` (or `ts_setup`) function.

To remove `ts_config` from all tests/* applications I have to move it to `ts_setup` but also to `ts_open`. From tests applications there is no difference because always after `ts_open` next step is `ts_config`.

But I'm a little bit worried about some external applications which are using `tslib` as a library. I guess in most cases flow is this same as for tests applications `ts_open` -> `ts_config`; so it will be changed to `ts_open` -> `ts_config` (called internally by `ts_open`) -> `ts_config`.

We can try to detect 2nd `ts_config` call and terminate this function but this is ugly workaround.
Alternatively I can keep original `ts_open` implementation (i.e. without `ts_config` inside) but then tests application will look like

```
if(name_is_defined) {
  ts = ts_open(...);
  ts_config(ts);
} else {
  ts = ts_setup(...);
}
```

which is also not nice and for sure doesn't simplify existing implementation.

**Comment by merge** [comment]
We won't change `ts_open()` obviously. We won't change any API! We can only add `ts_setup()`.

Let's move the "if name is defined by calling user" to our `ts_setup()`: It can look like `ts_setup(int blocking, char *inputpath)` and (if non-NULL) of course use it, if NULL, go through the list (and include calling `ts_config()`).

What do you think?

**Comment by filug** [comment]
Now I've understand your idea. 
Please check [9f37e9c](https://github.com/kergoth/tslib/pull/62/commits/9f37e9cd487c53de0790f39809dd3e289ef3e90b) commit.

`ts_setup` will use:

- defined by the user name, or if it's NULL,
- defined by the `TSLIB_TSDEVICE` name, or in case this variable is not defined,
- test predefined devices.

In case of success `ts_setup` will call `ts_config`.

I'd prefer to use `ts_setup(char *inputpath, int blocking)` rather than proposed by you `ts_setup(int blocking, char *inputpath)` but if there is a reason for this syntax I can correct it.

**Comment by merge** [comment]
I took your changes, but edited your second commit slightly:
* added documentation in README
* added Fixes tags in the commit message

I hope that's fine with you. Thanks for your help!

**Comment by filug** [comment]
That's absolutely fine. Thanks for your time and support.

**Pull request closed without merging**
