### PR TITLE
Ts uinput touch

### PR DESCRIPTION
**Pull request by hisar2626**
Hi Mr. Peter,
I dont know if i request in true section or not; im so sorry. I have an UDO board, Waveshare 7'' touchscreen. When i look udo website, http://udoo.org/forum/threads/connecting-5-lcd-screen-android.2455/
admin says "we have to compile kernel sources". I am poor at kernel programming and find your projects so i hope you may help me. I am using android 4.4.2 Kit kat in udoo now. I need to connect Waveshare 7'' touchscreen to UDOO board and use it. What should i do, can you help me pls? 

Thanks for your working and helps

### CODE REVIEW

**Comment by vpeter4** [comment]
Why did you send my commits as PR? I opened issue and if there would be interest from tslib maintainer I would send PR myself.

Also this small piece of sw will not help you on android.

**Comment by merge** [comment]
Hi @vpeter4  I picked up your waveshare plugin, so this can now be maintained upstream. Also, I put your ts_reconfig() on my list. I won't include this just now, but it's a nice idea. Just so you know. Thanks a lot for all this work!

**Comment by vpeter4** [comment]
Great news!
Maybe tslib will get little more attention in the future.

**Comment by merge** [comment]
So I took ts_reconfig, but I put it in ts_config.c. Please shout if you're not happy with my changes to your idea.

**Comment by vpeter4** [comment]
Whatever you think it's better. Initially I add in separate file just because there are already bunch of them for every operation. But seems logical to have it near ts_config.

One little off-topic thing I have in my mind is how to achieve calibration from some gui aplication (like from kodi in my case) and using ts_uinput daemon. I was thinking to write one extra plugin which would react on SIGUSR1 signal and collect calibration data and wrote calibration file. Like I did in my daemon. Do you have any better idea? The point is to not use ts_calibrate program from console.

**Comment by merge** [comment]
I'm not sure I get what you mean. ts_uinput uses calibrated data only. Any environment using Linux' input events can directly use it.

Why exactly would you re-implement ts_calibrate and don't execute it itself?

**Comment by vpeter4** [comment]
Because I don't want to use ts_calibrate program but would like to calibrate from Kodi like [this](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/service/touchscreen/source/resources/screenshot-001.png).
Anyway, just forget this - not related to tslib.

**Pull request closed without merging**
