### PR TITLE
allow toolchain to pass in shared linker flags

### PR DESCRIPTION
**Pull request by jwinarske**
This fix allows a cmake toolchain file to affect the linking of plugin modules.  Usage in a CMake toolchain might be:

    `set(CMAKE_SHARED_LINKER_FLAGS "-v -fuse-ld=lld")`

In the case above it allows the plugins to be linked via LLVM lld.

### CODE REVIEW

**Comment by merge** [comment]
@skirk could you have a quick look?

**Comment by skirk** [comment]
Hi @jwinarske, 

Are those flags not automatically added to link line if you configure the lib with BUILD_SHARED_LIBS=ON? 

If not, I would use target_link_options call to set any extra link flags.

**Comment by jwinarske** [comment]
Hi @skirk 

BUILD_SHARED_LIBS=ON has no affect.

I'm setting CMAKE_SHARED_LINKER_FLAGS in a CMAKE_TOOLCHAIN_FILE, which is passed with CMAKE_ARGS in an ExternalProject_Add.  The values from the toolchain file are not picked up, unless I explicitly add it; as in my PR.

target_link_options is only present with CMake > 3.12.14

**Comment by skirk** [comment]
The plugins are added as modules so they have their own CMAKE_MODULE_LINKER_FLAGS variable.
I've tried running the following CMakeList.txt:

```
cmake_minimum_required(VERSION 3.10)
include(ExternalProject)
set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/toolchain.cmake")
ExternalProject_Add(tslib
	GIT_REPOSITORY https://github.com/kergoth/tslib.git
        CMAKE_ARGS -DCMAKE_TOOLCHAIN_FILE:PATH=${CMAKE_TOOLCHAIN_FILE})
```
where the toolchain.cmake is:
```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_MODULE_LINKER_FLAGS "-some-flag")
```

And I'm getting complation error: 
`cc: error: unrecognized command line option ‘-some-flag’`

So in this test the flag seems to get through. 
Could you test that?

**Comment by jwinarske** [comment]
@skirk that worked great.  Thanks!

**Pull request closed without merging**
