### PR TITLE
CMake support + minor changes

### PR DESCRIPTION
**Pull request by skirk**
Hi, 

This PR adds a fairly complete build system replication using CMake. I'd be happy if you'd review the the commit and give feedback if any. I added minimal documentation how to build and use the cmake build system. The documentation assumes the user knows a bit of cmake before hand. 

Some changes on the configuration line are:
- --enable-input=static => -Dstatic-input=ON
- --enable-input => -Denable-input=ON

However, I would probably use keyword like _builtin_ instead _static_ in the above case as static implies the plugin will be built as a static library, where as in reality it's "embedded" into the core tslib.
What do you think?

Unfortunately I don't have very good test capabilities to test the binaries at the moment so I'd be happy if you could give it a spin and report any issues. I'm happy to do any fixes/changes or add any missing features you might come across. 

Thanks,
Tuomo

### CODE REVIEW

**Comment by merge** [comment]
Thanks. Not yet tested, but looks not bad overall. First question that comes up is: how did you decide where to define TS_POINTERCAL? This is used by ts_calibrate and the "linear" plugin only.

I'll take a closer look as I have time.

**Comment by skirk** [comment]
At the moment is added as a PUBLIC definition to tslib core, so whatever links against that will inherit that definition as well. In the autotools version the definition is added to all plugins and tests too.

If you'd rather have it defined in only those two instances I can do some modifications.

**Comment by skirk** [comment]
I've conducted few more tests today and identified some issues which I've rectified in the above commits.

**Comment by merge** [comment]
I like it. I only would like to have one change: build shared libraries and plugins by default, and document how to build statically (revert the behaviour).

And if you are willing to keep around in case of questions / bugs in the CMake build, I'd like to merge it then.

**Comment by skirk** [comment]
Thanks. Sure, I'm around to fix any bugs and answer questions.

I will apply the requested changes when I get a change.

**Comment by skirk** [comment]
The default behaviour now builds the tslib as shared library and plugins as modules that are loadable using dlopen

**Comment by merge** [comment]
Looks quite good! I see one thing missing: The whatever equivalent in cmake is to:
```
AX_DEFINE_SUBST([LIBTS_VERSION_CURRENT], [$LT_CURRENT], [library current number])
AX_DEFINE_SUBST([LIBTS_VERSION_REVISION], [$LT_REVISION], [library revision number])
AX_DEFINE_SUBST([LIBTS_VERSION_AGE], [$LT_AGE], [library age number])
```
in configure.ac.

These are then defined in config.h which is used by the library. Can you define those in cmake too? I'd be fine with keeping version-number up-to-date manually in one CMakeLists file, in addition to configure.ac...

thanks.

**Comment by skirk** [comment]
I think the commit above adds that feature. Let me know if that works

**Comment by merge** [comment]
FWIW I added you to the mailmap and THANKS file. Feel free to change the mailmap entries in case you want to have them differently. so: thanks so far!

**Comment by skirk** [comment]
Cool, that email is fine. Thanks for merging

**Pull request merged**
